# Problem Set 2
# Aditya Balaram

## Problem 1 from the Standard Library chapter

In [1]:
def list_stats(L):
    '''
    This function returns the maximum, minimum and average of the entries in a list
    
    Args:
    L (List): The list from which these values are to be computed
    
    Returns:
    The maximum, minimum and average of the list (in that specific order)
    '''
    return max(L), min(L), (sum(L)/len(L))

In [2]:
list_stats([10,30,0,4,100])

(100, 0, 28.8)

#### The above function is executed in one line

# Problem 2 from the Standard Library chapter

In [3]:
# Check if int's are mutable
int_val_1 = 4
int_val_2 = int_val_1
int_val_2 = 13
if(int_val_1 == int_val_2):
    print('int data type is mutable')
else:
    print('int data type is immutable')
        

int data type is immutable


In [4]:
# Check if strings are mutable
str_val_1 = 'aditya'
str_val_2 = str_val_1
str_val_2 = 'balaram'
if(str_val_1 == str_val_2):
    print('str data type is mutable')
else:
    print('str data type is immutable')

str data type is immutable


In [5]:
# Check if lists are mutable
list_1 = [1,2,3,4]
list_2 = list_1
list_2[1] = 3
if(list_1 == list_2):
    print('Lists are mutable')
else:
    print('Lists are immutable')

Lists are mutable


In [6]:
#Check if tuples are mutable
tuple_1 = (1,2,3,4)
tuple_2 = tuple_1
tuple_2 += (1,)
if(tuple_1 == tuple_2):
    print('Tuples are mutable')
else:
    print('Tuples are immutable')

Tuples are immutable


In [7]:
#Check if sets are mutable
set_1 = {1,2,3}
set_2 = set_1
set_2.remove(3)    #This removes the element 3 from the set
if(set_1 == set_2):
    print('Sets are mutable')
else:
    print('Sets are immutable')

Sets are mutable


In [8]:
set_2    #3 was removed from set_2 as expected

{1, 2}

In [9]:
set_1    #3 was removed from set_1 since a separate object wasn't created, implying that sets are mutable

{1, 2}

# Problem 3 from the Standard Library chapter

### I'm not explicitly creating a module called Calculator.py but if the first set of functions were saved in a file by that name, one could execute it from the command line and then follow this up by saving the hypotenuse calculator in a separate Python file, execute it, and then call the function hyp_calc(a,b).

### I presume I could do this by using the command %run -i Calculator.py but I've already defined the functions here and it feels like unnecessary work. Ideally, I should have just saved everything in different .py files. Hope that's ok. Sorry about this.

In [10]:
def sum_calc(a,b):
    '''
    This function computes the sum of two real valued arguments
    
    Args:
    a,b (Scalars): Two real values
    
    '''
    return (a+b)

def prod_calc(a,b):
    '''
    This function computes the product of two real valued arguments
    
    Args:
    a,b (Scalars): Two real values
    
    '''
    return (a*b)

import math

In [11]:
def hyp_calc(a,b):
    '''
    This function computes the length of the hypotenuse for a right angle triangle with
    the other two sides input by the user
    
    Args:
    
    a,b (Scalar): Positive real values
    
    Returns:
    
    hyp (Scalar): Length of hypotenuse
    
    '''
    #Compute the squares of the two sides
    dist_1_sq = prod_calc(a,a)
    dist_2_sq = prod_calc(b,b)
    
    #Compute the sum of the squares
    sum_val = sum_calc(dist_1_sq,dist_2_sq)
    
    #Compute the square root
    hyp = math.sqrt(sum_val)
    
    return hyp

In [12]:
hyp_calc(3,4)

5.0

# Problem 1 from the Numpy chapter

In [13]:
import numpy as np

def mat_dot_prod():
    '''
    Compute the dot product of matrices A and B as defined in Problem 1 of the Numpy chapter
    
    Returns:
    
    dot_prod: 2x4 matrix which is the dot product of A and B
    
    '''
    
    A = np.array([[3, -1, 4],[1, 5, -9]])
    B = np.array([[2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3]])
    
    dot_prod = np.dot(A,B)
    
    return dot_prod

In [14]:
mat_dot_prod()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

# Problem 2 from the Numpy chapter

In [15]:
def Cayley_Hamilton_Demo():
    '''
    Provides a demonstration of the Cayley Hamilton theorem for the matrix A defined in the Numpy chapter
    
    Returns:
    
    mat_final: Result of computing -A^3 + 9A^2 - 15A
    
    '''
    
    A = np.array([[3, 1, 4],[1, 5, 9],[-5, 3, 1]])
    
    square_term = np.dot(A,A)
    cubic_term = np.dot(square_term,A)
    
    mat_final = (-1 * cubic_term) + (9 * square_term) + (-15 * A)
    
    
    return mat_final

In [16]:
Cayley_Hamilton_Demo()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Problem 5 from the Numpy chapter

In [17]:
def array_stacking():
    '''
    Stacks defined matrices in the manner specified in the problem
    
    Returns:
    
    stacked (2-D array): The matrix as specified in the problem
    '''
    
    # Create specified matrices 
    A = np.arange(6).reshape(3,2).T
    I = np.eye(3)
    B = np.full_like(I,3)
    B = np.tril(B)
    C = -2 * I
    
    I_2 = np.eye(2)
    
    Block_Row_1 = np.hstack((np.zeros_like(I),A.T,np.eye(3)))
    Block_Row_2 = np.hstack((A,np.zeros_like(I_2),np.zeros_like(A)))
    Block_Row_3 = np.hstack((B,np.zeros_like(A.T),C))
    
    stacked = np.vstack((Block_Row_1,Block_Row_2,Block_Row_3))
    
    return stacked

In [18]:
array_stacking()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

# Problem 1 from the Object Oriented Programming chapter

In [19]:
class Backpack:
    """A Backpack object class. Has a name, color, maximum size, and a list of contents.
    
    Attributes:
    name (str): the name of the backpack's owner.
    color (str): the color of the backpack.
    max_size (int): the maximum number of items that can be in the backpack. This is fixed at 5
    contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size = 5): # This function is the constructor.
        
        """Set the name and initialize an empty list of contents.
        Parameters:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum number of items that can be in the backpack. This is fixed at 5
        """
        self.name = name
        self.color = color
        self.contents = []
        self.max_items = max_size
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents as long as there is space remaining in the backpack."""
        if(len(self.contents) < self.max_items):
            self.contents.append(item)
        else:
            print('No room!')

    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """Remove all items from the backpack"""
        self.contents.clear()

In [20]:
def test_backpack():
    testpack = Backpack("Barry", "black") # Instantiate the object.
    if testpack.name != "Barry": # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item) # Test a method.
    print("Contents:", testpack.contents)

In [21]:
test_backpack()    #This is the test suggested in the Problem itself

Contents: ['pencil', 'pen', 'paper', 'computer']


In [22]:
def test_backpack_2():
    testpack = Backpack("Barry", "black") # Instantiate the object.
    if testpack.name != "Barry": # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item) # Test a method.
    print("Contents:", testpack.contents)
    
    testpack.put('bigger computer')    #Adds a fifth item to the backpack
    print("Contents:", testpack.contents)
    
    
    print("Attempting to add a sixth item")
    testpack.put('lunch')    #Attempts to add a sixth item
    print("Contents:", testpack.contents)
    
    print("Dump all items from the backpack")
    testpack.dump()    #Empty the entire backpack
    print("Contents:", testpack.contents)
    
    print("Color of the backpack is:", testpack.color)
    print("Owner of the backpack is:", testpack.name)

In [23]:
test_backpack_2()

Contents: ['pencil', 'pen', 'paper', 'computer']
Contents: ['pencil', 'pen', 'paper', 'computer', 'bigger computer']
Attempting to add a sixth item
No room!
Contents: ['pencil', 'pen', 'paper', 'computer', 'bigger computer']
Dump all items from the backpack
Contents: []
Color of the backpack is: black
Owner of the backpack is: Barry


# Problem 2 from the Object Oriented Programming chapter

In [24]:
# Inherit from the Backpack class in the class definition.
class Jetpack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class.
    A jetpack has some amount of fuel in it that can be burned in order to fly.
    
    Attributes:
    name (str): the name of the jetpack's owner.
    color (str): the color of the jetpack.
    max_size (int): the maximum number of items that fit in the jetpack - fixed at 2
    fuel_amt (int): the amount of fuel in the jetpack to start with - default of 10
    """
    
    def __init__(self, name, color, max_size=2):
        """Use the Backpack constructor to initialize the name, color,
        fuel_amt and max_size attributes. A jetpack only holds 3 items by default and
        10 units of fuel to start with.
        
        Parameters:
        name (str): the name of the jetpack's owner.
        color (str): the color of the jetpack.
        max_size (int): the maximum number of items that can fit inside.
        """
        Backpack.__init__(self, name, color, max_size)
        self.fuel_amt = 10
        
    def fly(self, burn_amt):
        """Use the jetpack to consumer 'burn_amt' units of fuel if possible.
        
        Args:
        burn_amt(int): Amount of fuel that is to be consumed
        """
        
        if(self.fuel_amt > burn_amt):
            self.fuel_amt = self.fuel_amt - burn_amt
        else:
            print('Not enough fuel!')
        
    def dump(self):
        """Empty contents and fuel from jetpack"""
        self.contents.clear()
        self.fuel_amt = 0

In [25]:
my_jetpack = Jetpack("Aditya", "Red")    #Creates a Jetpack object

my_jetpack.put("Safety fuel")    #Stores "Safety fuel" in the Jetpack 

my_jetpack.fly(3)    #Fly using 3 units of fuel 

print("Amount of remaining fuel:", my_jetpack.fuel_amt)
print("Contents of jetpack:", my_jetpack.contents)

Amount of remaining fuel: 7
Contents of jetpack: ['Safety fuel']


In [26]:
my_jetpack.put("A")
my_jetpack.put("B")     #Try to add more than the maximum allowable size

print("Contents of jetpack:", my_jetpack.contents)

my_jetpack.fly(13)    #Try to use more fuel than available

my_jetpack.dump()    #Empty contents and fuel

print("Amount of remaining fuel:", my_jetpack.fuel_amt)
print("Contents of jetpack:", my_jetpack.contents)

No room!
Contents of jetpack: ['Safety fuel', 'A']
Not enough fuel!
Amount of remaining fuel: 0
Contents of jetpack: []
